# Generated by Django 5.2.17 on 2026-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=255, verbose_name='اسم المهندس')),
                ('registration_num', models.CharField(max_length=50, verbose_name='رقم القيد')),
                ('division', models.CharField(max_length=255, verbose_name='الشعبة الهندسية')),
                ('registry_num', models.CharField(max_length=50, verbose_name='رقم السجل')),
                ('category', models.CharField(choices=[('engineer', 'مهندس'), ('consultant', 'مهندس استشاري'), ('consultant_concrete', 'مهندس استشاري تصميم و انشءات خرسانية'), ('specialized_office', 'مكتب نوعي'), ('multi_office', 'مكتب متعدد')], max_length=50, verbose_name='فئة المهندس')),
                ('certificate_count', models.PositiveIntegerField(verbose_name='عدد الشهادات')),
                ('pickup_date', models.DateField(verbose_name='تاريخ الاستلام')),
                ('pickup_slot', models.CharField(choices=[('morning', 'فترة صباحية'), ('evening', 'فترة مسائية')], max_length=20, verbose_name='الفترة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
            ],
            options={
                'verbose_name': 'طلب استلام شهادة',
                'verbose_name_plural': 'طلبات استلام الشهادات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyndicateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit_engineer', models.PositiveIntegerField(default=100, verbose_name='حد المهندس العادي الشهري')),
                ('monthly_limit_consultant', models.PositiveIntegerField(default=140, verbose_name='حد المهندس الاستشاري الشهري')),
                ('monthly_limit_concrete_consultant', models.PositiveIntegerField(default=180, verbose_name='حد المهندس الاستشاري خرسانة الشهري')),
                ('monthly_limit_specialized_office', models.PositiveIntegerField(default=250, verbose_name='حد المكتب النوعي الشهري')),
                ('monthly_limit_multi_office', models.PositiveIntegerField(default=450, verbose_name='حد المكتب المتعدد الشهري')),
                ('daily_limit_morning', models.PositiveIntegerField(default=150, verbose_name='الحد الأقصى للفترة الصباحية اليومي')),
                ('daily_limit_evening', models.PositiveIntegerField(default=200, verbose_name='الحد الأقصى للفترة المسائية اليومي')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255, verbose_name='توكن بوت تلجرام')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرف شات تلجرام (المستلم)')),
            ],
            options={
                'verbose_name': 'إعدادات النقابة',
                'verbose_name_plural': 'إعدادات النقابة',
            },
        ),
    ]
